### ISSUE TITLE
当前release分支，leanback版崩溃,mobile版正常

### ISSUE THREAD

**Issue by phoenixsky** [FongMi/TV#195]
日志如下
`java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/servlet/http/HttpServlet;
at org.fourthline.cling.android.AndroidUpnpServiceConfiguration.createStreamServer(AndroidUpnpServiceConfiguration.java:110)
at org.fourthline.cling.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:427)
at org.fourthline.cling.transport.RouterImpl.enable(RouterImpl.java:132)
at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:91)
at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87)
at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:54)
at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54)
at com.android.cast.dlna.dmr.DLNARendererService.onCreate(DLNARendererService.kt:70)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4770)
at android.app.ActivityThread.-Nest$mhandleCreateService(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2269) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:8401) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.servlet.http.HttpServlet" on path: DexPathList[[zip file "/data/app/~~jS3rRzPtzkXVZEbARztBQw==/com.fongmi.android.tv-bG3Z49H4NAD7Nadbt7v6uA==/base.apk"],nativeLibraryDirectories=[/data/app/~~jS3rRzPtzkXVZEbARztBQw==/com.fongmi.android.tv-bG3Z49H4NAD7Nadbt7v6uA==/lib/arm64, /data/app/~~jS3rRzPtzkXVZEbARztBQw==/com.fongmi.android.tv-bG3Z49H4NAD7Nadbt7v6uA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at org.fourthline.cling.android.AndroidUpnpServiceConfiguration.createStreamServer(AndroidUpnpServiceConfiguration.java:110)  at org.fourthline.cling.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:427)  at org.fourthline.cling.transport.RouterImpl.enable(RouterImpl.java:132)  at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:91)  at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87)  at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:54)  at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54)  at com.android.cast.dlna.dmr.DLNARendererService.onCreate(DLNARendererService.kt:70)  at android.app.ActivityThread.handleCreateService(ActivityThread.java:4770)  at android.app.ActivityThread.-Nest$mhandleCreateService(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2269) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:211) 
at android.os.Looper.loop(Looper.java:300) 
at android.app.ActivityThread.main(ActivityThread.java:8401) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) `

**Comment by FongMi** [comment]
測試沒問題。

**Comment by WoKee** [comment]
添加引用     implementation 'javax.servlet:javax.servlet-api:4.0.1' 即可

**Comment by FongMi** [comment]
奇怪了，為啥我包就沒問題呢。

**Comment by phoenixsky** [comment]
> 添加引用 implementation 'javax.servlet:javax.servlet-api:4.0.1' 即可

🐂🍺，已修复
