### ISSUE TITLE
live not working on x86

### ISSUE THREAD

**Issue by hellodword** [FongMi/TV#198]
I use this project with [wsa](https://learn.microsoft.com/en-us/windows/android/wsa/), and the armeabi_v7a version works well.

However, I am curious to explore whether the x86 version offers better performance, so I'm currently compiling the x86 version.

> https://learn.microsoft.com/en-us/windows/android/wsa/#building-universal-apks
> Windows Subsystem for Android™️ utilizes Intel Bridge Technology to enable Arm applications on x86 based processors. Arm applications will run on Arm-based processors natively. The emulation layer will induce a performance overhead – for optimal performance, submit your application for both the x86-64 and Arm64 architectures.

(Maybe `x86-64` is also needed)

https://github.com/FongMi/TV/blob/8531414ad0ce2a89fb3ec8db1e9452f6f314e4cd/app/build.gradle#L35-L46

And with this patch: https://github.com/FongMi/TV/pull/197/files , I can build all of them.

The `mobilePythonArmeabi_v7a/debug/mobile-python-armeabi_v7a.apk` works well, but live of `mobilePythonX86/debug/mobile-python-x86.apk` does not, with [same source](https://github.com/gaotianliuyun/gao/blob/master/0821.json).

![Peek 2023-12-23 05-04](https://github.com/FongMi/TV/assets/46193371/6ed84c92-1e8f-491a-857b-1043113e86e6)

```
12-23 13:03:55.694  5544  5544 E ngmi.android.tv: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer._stop() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1stop and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1stop__)
12-23 13:03:55.695  5544  5544 D AndroidRuntime: Shutting down VM
12-23 13:03:55.695  5544  5544 E AndroidRuntime: FATAL EXCEPTION: main
12-23 13:03:55.695  5544  5544 E AndroidRuntime: Process: com.fongmi.android.tv, PID: 5544
12-23 13:03:55.695  5544  5544 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer._stop() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1stop and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1stop__)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer._stop(Native Method)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer.stop(IjkMediaPlayer.java:363)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at tv.danmaku.ijk.media.player.ui.IjkVideoView.stop(IjkVideoView.java:232)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at com.fongmi.android.tv.player.Players.stopIjk(Players.java:460)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at com.fongmi.android.tv.player.Players.stop(Players.java:366)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at com.fongmi.android.tv.ui.activity.LiveActivity.setLive(LiveActivity.java:675)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at com.fongmi.android.tv.ui.dialog.LiveDialog.onItemClick(LiveDialog.java:74)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at com.fongmi.android.tv.ui.adapter.LiveAdapter.lambda$onBindViewHolder$0$com-fongmi-android-tv-ui-adapter-LiveAdapter(LiveAdapter.java:65)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at com.fongmi.android.tv.ui.adapter.LiveAdapter$$ExternalSyntheticLambda2.onClick(Unknown Source:4)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at android.view.View.performClick(View.java:7542)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7519)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:29476)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7918)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-23 13:03:55.695  5544  5544 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer._stop() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1stop and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1stop__)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at tv.danmaku.ijk.media.player.IjkMediaPlayer._stop(Native Method)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at tv.danmaku.ijk.media.player.IjkMediaPlayer.stop(IjkMediaPlayer.java:363)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at tv.danmaku.ijk.media.player.ui.IjkVideoView.stop(IjkVideoView.java:232)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at com.fongmi.android.tv.player.Players.stopIjk(Players.java:460)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at com.fongmi.android.tv.player.Players.stop(Players.java:366)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at com.fongmi.android.tv.ui.activity.LiveActivity.setLive(LiveActivity.java:675)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at com.fongmi.android.tv.ui.dialog.LiveDialog.onItemClick(LiveDialog.java:74)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at com.fongmi.android.tv.ui.adapter.LiveAdapter.lambda$onBindViewHolder$0$com-fongmi-android-tv-ui-adapter-LiveAdapter(LiveAdapter.java:65)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at com.fongmi.android.tv.ui.adapter.LiveAdapter$$ExternalSyntheticLambda2.onClick(Unknown Source:4)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at android.view.View.performClick(View.java:7542)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at android.view.View.performClickInternal(View.java:7519)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at android.view.View$PerformClick.run(View.java:29476)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at android.os.Handler.handleCallback(Handler.java:942)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at android.os.Handler.dispatchMessage(Handler.java:99)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at android.os.Looper.loopOnce(Looper.java:201)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at android.os.Looper.loop(Looper.java:288)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at android.app.ActivityThread.main(ActivityThread.java:7918)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at java.lang.reflect.Method.invoke(Native Method)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-23 13:03:55.695  5544  5544 E CustomActivityOnCrash:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Any idea? Thanks!

**Comment by hellodword** [comment]
Maybe related issue https://github.com/CaiJingLong/flutter_ijkplayer/issues/164#issuecomment-558261659

I will give it a try

**Comment by hellodword** [comment]
OK, found the issue

https://github.com/FongMi/TV/tree/release/ijkplayer/src/main/jniLibs

**Comment by hellodword** [comment]
```
./forcetech/src/main/assets/libmitv.so:                      ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./forcetech/src/main/jniLibs/armeabi-v7a/libmitv.so:         ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
./forcetech/src/main/jniLibs/armeabi-v7a/libp2p.so:          ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./forcetech/src/main/jniLibs/armeabi-v7a/libp3p.so:          ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./forcetech/src/main/jniLibs/armeabi-v7a/libp4p.so:          ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./forcetech/src/main/jniLibs/armeabi-v7a/libp5p.so:          ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./forcetech/src/main/jniLibs/armeabi-v7a/libp6p.so:          ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./forcetech/src/main/jniLibs/armeabi-v7a/libp7p.so:          ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
./forcetech/src/main/jniLibs/armeabi-v7a/libp8p.so:          ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./forcetech/src/main/jniLibs/armeabi-v7a/libp9p.so:          ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./ijkplayer/src/main/jniLibs/arm64-v8a/libijkffmpeg.so:      ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
./ijkplayer/src/main/jniLibs/arm64-v8a/libijksdl.so:         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=30be9ec8f5570e1ca5f61f198706cb8f42a8d495, stripped
./ijkplayer/src/main/jniLibs/arm64-v8a/libplayer.so:         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a3f237897eeabcf030e8a4a89ca7bc55a46a1b2f, stripped
./ijkplayer/src/main/jniLibs/armeabi-v7a/libijkffmpeg.so:    ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
./ijkplayer/src/main/jniLibs/armeabi-v7a/libijksdl.so:       ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=d0da5146e9497d85bbb3ed3500ccb6b959006a33, stripped
./ijkplayer/src/main/jniLibs/armeabi-v7a/libplayer.so:       ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=b4bfd3db585f5aa5a43a4f77e9d8d652364affa6, stripped
./jianpian/src/main/jniLibs/arm64-v8a/libjpa.so:             ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0dcdc06484f6b33799f3a6b46bf69ed0f493daa5, stripped
./jianpian/src/main/jniLibs/armeabi-v7a/libjpa.so:           ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=2babb63618b232f368facc18a6746d405773fe6e, stripped
./other/jniLibs/libjpa_arm64_v8a.so:                         ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0dcdc06484f6b33799f3a6b46bf69ed0f493daa5, stripped
./other/jniLibs/libjpa_armeabi_v7a.so:                       ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=2babb63618b232f368facc18a6746d405773fe6e, stripped
./other/jniLibs/libmitv.so:                                  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./other/jniLibs/libp2p-jp-arm64_v8a.so:                      ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0dcdc06484f6b33799f3a6b46bf69ed0f493daa5, stripped
./other/jniLibs/libp2p-jp-armeabi_v7a.so:                    ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=2babb63618b232f368facc18a6746d405773fe6e, stripped
./other/jniLibs/libp2p.so:                                   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./other/jniLibs/libp3p.so:                                   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./other/jniLibs/libp4p.so:                                   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./other/jniLibs/libp5p.so:                                   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./other/jniLibs/libp6p.so:                                   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./other/jniLibs/libp7p.so:                                   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
./other/jniLibs/libp8p.so:                                   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./other/jniLibs/libp9p.so:                                   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./other/jniLibs/libtvcore.so:                                ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
./other/jniLibs/libxl_stat_arm64_v8a.so:                     ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f7660cdf1a3b6981e76696c9a2233ca0732189c3, stripped
./other/jniLibs/libxl_stat_armeabi_v7a.so:                   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=d45d91a5adc347a7d00d6894934c937f478d93b3, stripped
./other/jniLibs/libxl_thunder_sdk_arm64_v8a.so:              ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ca94520e22b97b995f39a4a76d0b35c8c5b93b3f, stripped
./other/jniLibs/libxl_thunder_sdk_armeabi_v7a.so:            ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=ca08859b0d63c149c26c1a2561ce3888e4f6c797, stripped
./thunder/src/main/jniLibs/arm64-v8a/libxl_stat.so:          ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f7660cdf1a3b6981e76696c9a2233ca0732189c3, stripped
./thunder/src/main/jniLibs/arm64-v8a/libxl_thunder_sdk.so:   ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ca94520e22b97b995f39a4a76d0b35c8c5b93b3f, stripped
./thunder/src/main/jniLibs/armeabi-v7a/libxl_stat.so:        ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=d45d91a5adc347a7d00d6894934c937f478d93b3, stripped
./thunder/src/main/jniLibs/armeabi-v7a/libxl_thunder_sdk.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=ca08859b0d63c149c26c1a2561ce3888e4f6c797, stripped
./zlive/src/main/jniLibs/armeabi-v7a/libcore.so:             ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, Go BuildID=dOLBM0HpJTJ_yfSK1PRL/PIyjrtRVCSjios4sXSED/W7UgWSrcgxhZtXth-vVn/AHBea4J6-HEuvwkMK1S1, stripped
./zlive/src/main/jniLibs/armeabi-v7a/libjnidispatch.so:      ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, not stripped
```

There're some prebuilt libraries in the project, and no x86 or x86-64 I guess, could you provide source code of them? (Because some of them are forked version)

**Comment by cai512** [comment]
#### 1. 用啥模擬器 還是 wsa , wsa 有多垃圾，不如雷電

**Comment by hellodword** [comment]
> 用啥模擬器 

平时在手机和电视上用 tvbox，偶尔在 PC 上用用也无不可

> 還是 wsa , wsa 有多垃圾，不如雷電

WSA 是微软的，雷电是不知名小厂的，或许你选择模拟器时不介意安全性，但我介意

并且这个 issue 与选择哪款模拟器没有关系，只要 abi 是 x86 或者 x86_64 都会异常，我现在更希望能够获得完整源码尝试修复编译和贡献代码

**Comment by FongMi** [comment]
ijk 沒有 x86，所以建議用 exo 。
https://github.com/CatVodTVOfficial/TVBoxOSC_ijkplayer
